<?php 
    //This class is generated by SiteGenerator to use PHP before HTML tags

    class PHPHeader{

        function __construct(){
            
        }

        static function Init(){

            $rpc = new rpc();
            //Session start
            $rpc->dorpc('SessionController','InitSession');
        }

        static function Random($length = 8){
            return bin2hex(random_bytes($length));
        }

        static function Redirect($Url){
            echo '<meta http-equiv="refresh" content="0;url='.$Url.'">';
        }
    }
?>